#-------------------------------------------------------------------------------------------
#  Copyright (c) 2016-2025.  SupportVectors AI Lab
#
#  This code is part of the training material, and therefore part of the intellectual property.
#  It may not be reused or shared without the explicit, written permission of SupportVectors.
#
#  Use is limited to the duration and purpose of the training at SupportVectors.
#
#  Author: SupportVectors AI Training
#-------------------------------------------------------------------------------------------

cohort: Spring 2025

current_task: tree-classification # mnist-classification #

mnist-classification:
  data: /Users/chandarl/data/mnist
  results: /Users/chandarl/results/mnist
  num_channels: 1
  num_classes: 10
  image_size: 28
  nz: 100
  ngf: 56 # number of generator feature maps
  ndf: 56 # number of discriminator feature maps
  
tree-classification:
  data: /Users/chandarl/data/trees
  results: /Users/chandarl/results/trees
  num_channels: 3
  num_classes: 2
  image_size: 64
  nz: 100
  ngf: 64 # number of generator feature maps
  ndf: 64 # number of discriminator feature maps