#-------------------------------------------------------------------------------------------
#  Copyright (c) 2016-2025.  SupportVectors AI Lab
#
#  This code is part of the training material, and therefore part of the intellectual property.
#  It may not be reused or shared without the explicit, written permission of SupportVectors.
#
#  Use is limited to the duration and purpose of the training at SupportVectors.
#
#  Author: SupportVectors AI Training
#-------------------------------------------------------------------------------------------

cohort: Spring 2025

mnist-classification:
  data: /Users/chandarl/data
  results: /Users/chandarl/results 

tree-classification:
  data: /Users/chandarl/data/trees
  results: /Users/chandarl/results/autoencoder_models

other-images:
  data: /Users/chandarl/data/other_images
